### ISSUE TITLE
How to predict instance with out label in test part?

### ISSUE THREAD

**Issue by fourseven471** [thunlp/FewRel#10]
In framework.eval()  
->support, query, label = eval_dataset.next_batch(B, N, K, Q, noise_rate=noise_rate)

how to get support set from test dataset without labels.

**Comment by gaotianyu1350** [comment]
The test set of FewRel is reserved for online evaluation and you can refer to the [website](http://www.zhuhao.me/fewrel/). If you have your own test set with no labels, you need to modify the function ``next_batch``. I'm not sure the definition of ''without labels''. If you do not have labels for all the instances, you cannot do few-shot since you cannot sample the support set at all.

**Comment by herbertchen1** [comment]
https://github.com/thunlp/FewRel/issues/10?_pjax=%23js-repo-pjax-container#issuecomment-497537249
hi , will the test set be released since the dataset has been conquered....
Without the test set ，it might be hard to get a fair comparison with your nice paper《Hybrid Attention-Based Prototypical Networks for Noisy Few-Shot Relation Classification》，or we have to submit the code to the leaderboard?

**Comment by gaotianyu1350** [comment]
Hi~ We believe that there is still space for improvement on this task, so sorry, the answer is no. If you'd like to evaluate your models under noise setting in the paper, we are trying to make a new online service. For now, you can email me your model and instruction, and I can help you evaluate on the test set. Sorry for the inconvenience~
