### ISSUE TITLE
The method for DA seems unable to work on other datasets. 

### ISSUE THREAD

**Issue by broken-dream** [thunlp/FewRel#32]
Hello, i 'm trying  the DA method(the basic one, not bert pair) on SCIERC, a dataset for scientific relation extraction, but found the result is poor. I also run it without DA part and compared it with the result of using DA, found that two results are similar. I made same comparison on other datasets(nty, semeval, semeval-2018-task7) and got the same result. I want to know why the method can gain a significant improvement(about 10%) on pubmed but not work on other datasets.

**Comment by gaotianyu1350** [comment]
Hi, the problem you mentioned is very interesting. This DA technique (adversarial training) is a widely-used one so I am not sure if it is due to poor choice of hyper-parameters or it is the problem of the algorithm. 

Maybe you can try to reproduce the result on PubMed to make sure that nothing goes wrong with the experiment? If that is not the case, the reason I can come up with is that the test domain is not so different from the training domain. For example, Semeval and NYT look similar to the Wikipedia domain, so using DA or not does not matter that much.

**Comment by broken-dream** [comment]
I reproduced the result on PubMed first and the result is similar to the one you published, so i think there is nothing wrong with the experiment.
I also consider the reason you mentioned, but it can not explain the result on SCIERC and semeval-2018-task7, which are constructed based on scientific paper. I think the gap bewteen the two domains(scientific paper and Wikipedia) is big enough.
