### ISSUE TITLE
Generating a dataset in your data format 

### ISSUE THREAD

**Issue by VahidehRt** [thunlp/FewRel#43]
Hi
I want to use your code for training and testing on my own data, but I don't know how I can generate a dataset in the format of train_wiki.json or val_wiki.json from raw text!  Is there any code available?
Thanks in advance

**Comment by gaotianyu1350** [comment]
Hi,

Our dataset is human annotated. For how we organize the annotation, you can refer to our [FewRel paper](https://www.aclweb.org/anthology/D18-1514.pdf). When you get both the raw text and the annotation, the rest is simple: just use any json tool (for example, `json` package in python) you like to change the format according to ours.

**Comment by VahidehRt** [comment]
Dear Tianyu,

I very much appreciate if you could help with this problem.

In train_wiki.json and val_wiki.json (which I use as test data), there are 64 and 16 separate classes (relations)!

-- Does it means that these 16classes of the test-data aren't belong to 64classes of the training-data? as the code (P177, P931, etc.) of classes(relation types) in two datasets are different as well... So how the algorithm labels the test-data while it hasnot seen its label before? Does it use the test-data' labels in training process?
 I completely confused as far as I studied in Fewshot learning, the input sample of test data belongs to one class of training data after running the algorithm...

-- I completely confused in generating my dataset... I have 50 relation types with one sample for each one as training-data and infinite number of test-data. The labels of test-data arenot known but they assume to belong to one of these 50 relation types. Is it possible to customize your algorithm for fewshot learning on it? 

Thank you so much in advance.

**Comment by gaotianyu1350** [comment]
For the first question, there are no interactions between train / Val / test relations because of the nature of N-way K-shot few-shot learning.

For the second question, this is not the classic few-shot learning paradigm, but more like supervised training with few samples. Please refer to our FewRel paper for more details.




On 08/18/2020 15:56, VahidehRt wrote:

Dear Tianyu,

I very much appreciate if you could help with this problem.

In train_wiki.json and val_wiki.json (which I use as test data), there are 64 and 16 separate classes (relations)!

-- Does it means that these 16classes of the test-data aren't belong to 64classes of the training-data? as the code (P177, P931, etc.) of classes(relation types) in two datasets are different as well... So how the algorithm labels the test-data while it hasnot seen its label before? Does it use the test-data' labels in training process?
I completely confused as far as I studied in Fewshot learning, the input sample of test data belongs to one class of training data after running the algorithm...

-- I completely confused in generating my dataset... I have 50 relation types with one sample for each one as training-data and infinite number of test-data. The labels of test-data arenot known but they assume to belong to one of these 50 relation types. Is it possible to customize your algorithm for fewshot learning on it?

Thank you so much in advance.
