### ISSUE TITLE
Where is the appendix?

### ISSUE THREAD

**Issue by BrambleXu** [thunlp/FewRel#7]
I can not find the appendix.

![image](https://user-images.githubusercontent.com/10768193/54980966-85f6db00-4fea-11e9-82ab-448bfb8be503.png)

**Comment by gaotianyu1350** [comment]
The appendix includes all the relations of training, validation, and test sets. Since we reserve the test set for [online evaluation](http://www.zhuhao.me/fewrel/), the appendix is not made public.

**Comment by chrisfalter** [comment]
Is it not possible to create a new appendix that contains only the following columns in a table of relations?
* Code ("P155", "P177", etc.)
* Name
* Description

Like this:
```
-----------------------------------------------------------------------------------
| Code | Name                       |  Description                                |
-----------------------------------------------------------------------------------
| P155 | is_parent_of               | e1 is adoptive or birth parent of e2.       |
| P177 | is_child_of                | e1 is adoptive or birth child of e2.        |
| .... | ....                       | ....                                        |
-----------------------------------------------------------------------------------

```

This would be a simple table with exactly one hundred rows.

This is hard for an outside volunteer because it would require making accurate inferences from a large volume of training and validation data. Some subtleties (e.g., _is_parent_of_ includes adoptive parents but does not include godparents) would require labor-intensive and mistake-prone work.

This should be relatively easy for a member of the original research team, since (I would assume) you have access to the notes you used when you organized your data labeling process.

I would ask that you reopen this issue and address it as soon as feasible. It would help me and no doubt many others to evaluate whether to invest time and resources in working with your data set vs. working with some other data set in the relation extraction space.

Thank you!

**Comment by gaotianyu1350** [comment]
Hi, thanks for the suggestion! You can now find the information from [pid2name.json](https://github.com/thunlp/FewRel/blob/master/data/pid2name.json), which includes PID, name and description for each relation.
